//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBimTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParameterMainHole1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParameterMainHole1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBimTool.Properties.ParameterMainHole1", typeof(ParameterMainHole1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_cao_bung.
        /// </summary>
        public static string Chieu_cao_bung {
            get {
                return ResourceManager.GetString("Chieu_cao_bung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_cao_co.
        /// </summary>
        public static string Chieu_cao_co {
            get {
                return ResourceManager.GetString("Chieu_cao_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_cao_napga.
        /// </summary>
        public static string Chieu_cao_napga {
            get {
                return ResourceManager.GetString("Chieu_cao_napga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_dai_BTlot.
        /// </summary>
        public static string Chieu_dai_BTlot {
            get {
                return ResourceManager.GetString("Chieu_dai_BTlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_dai_co.
        /// </summary>
        public static string Chieu_dai_co {
            get {
                return ResourceManager.GetString("Chieu_dai_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_dai_ga.
        /// </summary>
        public static string Chieu_dai_ga {
            get {
                return ResourceManager.GetString("Chieu_dai_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_day_Tuong.
        /// </summary>
        public static string Chieu_day_Tuong {
            get {
                return ResourceManager.GetString("Chieu_day_Tuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_day_TuongDuoi.
        /// </summary>
        public static string Chieu_day_TuongDuoi {
            get {
                return ResourceManager.GetString("Chieu_day_TuongDuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_day_TuongTren.
        /// </summary>
        public static string Chieu_day_TuongTren {
            get {
                return ResourceManager.GetString("Chieu_day_TuongTren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_rong_BTlot.
        /// </summary>
        public static string Chieu_rong_BTlot {
            get {
                return ResourceManager.GetString("Chieu_rong_BTlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_rong_co.
        /// </summary>
        public static string Chieu_rong_co {
            get {
                return ResourceManager.GetString("Chieu_rong_co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chieu_rong_ga.
        /// </summary>
        public static string Chieu_rong_ga {
            get {
                return ResourceManager.GetString("Chieu_rong_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_congMax.
        /// </summary>
        public static string D_congMax {
            get {
                return ResourceManager.GetString("D_congMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day_BT_lot.
        /// </summary>
        public static string Day_BT_lot {
            get {
                return ResourceManager.GetString("Day_BT_lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day_co_ga.
        /// </summary>
        public static string Day_co_ga {
            get {
                return ResourceManager.GetString("Day_co_ga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goc_LoMo1.
        /// </summary>
        public static string Goc_LoMo1 {
            get {
                return ResourceManager.GetString("Goc_LoMo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goc_LoMo2.
        /// </summary>
        public static string Goc_LoMo2 {
            get {
                return ResourceManager.GetString("Goc_LoMo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goc_LoMo3.
        /// </summary>
        public static string Goc_LoMo3 {
            get {
                return ResourceManager.GetString("Goc_LoMo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goc_LoMo4.
        /// </summary>
        public static string Goc_LoMo4 {
            get {
                return ResourceManager.GetString("Goc_LoMo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở tròn 1.
        /// </summary>
        public static string HOLE_CIRCLE_1 {
            get {
                return ResourceManager.GetString("HOLE_CIRCLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở tròn 2.
        /// </summary>
        public static string HOLE_CIRCLE_2 {
            get {
                return ResourceManager.GetString("HOLE_CIRCLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở tròn 3.
        /// </summary>
        public static string HOLE_CIRCLE_3 {
            get {
                return ResourceManager.GetString("HOLE_CIRCLE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở tròn 4.
        /// </summary>
        public static string HOLE_CIRCLE_4 {
            get {
                return ResourceManager.GetString("HOLE_CIRCLE_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hố ga.
        /// </summary>
        public static string HOLE_NAME {
            get {
                return ResourceManager.GetString("HOLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở vuông 1.
        /// </summary>
        public static string HOLE_RECT_1 {
            get {
                return ResourceManager.GetString("HOLE_RECT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở vuông 2.
        /// </summary>
        public static string HOLE_RECT_2 {
            get {
                return ResourceManager.GetString("HOLE_RECT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở vuông 3.
        /// </summary>
        public static string HOLE_RECT_3 {
            get {
                return ResourceManager.GetString("HOLE_RECT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗ mở vuông 4.
        /// </summary>
        public static string HOLE_RECT_4 {
            get {
                return ResourceManager.GetString("HOLE_RECT_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo1_B.
        /// </summary>
        public static string LoMo1_B {
            get {
                return ResourceManager.GetString("LoMo1_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo1_dV.
        /// </summary>
        public static string LoMo1_dV {
            get {
                return ResourceManager.GetString("LoMo1_dV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo1_H.
        /// </summary>
        public static string LoMo1_H {
            get {
                return ResourceManager.GetString("LoMo1_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo1_R.
        /// </summary>
        public static string LoMo1_R {
            get {
                return ResourceManager.GetString("LoMo1_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo2_B.
        /// </summary>
        public static string LoMo2_B {
            get {
                return ResourceManager.GetString("LoMo2_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo2_dV.
        /// </summary>
        public static string LoMo2_dV {
            get {
                return ResourceManager.GetString("LoMo2_dV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo2_H.
        /// </summary>
        public static string LoMo2_H {
            get {
                return ResourceManager.GetString("LoMo2_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo2_R.
        /// </summary>
        public static string LoMo2_R {
            get {
                return ResourceManager.GetString("LoMo2_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo3_B.
        /// </summary>
        public static string LoMo3_B {
            get {
                return ResourceManager.GetString("LoMo3_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo3_dV.
        /// </summary>
        public static string LoMo3_dV {
            get {
                return ResourceManager.GetString("LoMo3_dV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo3_H.
        /// </summary>
        public static string LoMo3_H {
            get {
                return ResourceManager.GetString("LoMo3_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo3_R.
        /// </summary>
        public static string LoMo3_R {
            get {
                return ResourceManager.GetString("LoMo3_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo4_B.
        /// </summary>
        public static string LoMo4_B {
            get {
                return ResourceManager.GetString("LoMo4_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo4_dV.
        /// </summary>
        public static string LoMo4_dV {
            get {
                return ResourceManager.GetString("LoMo4_dV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo4_H.
        /// </summary>
        public static string LoMo4_H {
            get {
                return ResourceManager.GetString("LoMo4_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoMo4_R.
        /// </summary>
        public static string LoMo4_R {
            get {
                return ResourceManager.GetString("LoMo4_R", resourceCulture);
            }
        }
    }
}
